name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # PyPI trusted publishing
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist
          merge-multiple: true
      - name: List wheels
        run: ls -l dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
        with:
          packages-dir: dist
          skip-existing: true
